[[headers]]
    for = "/*"
    [headers.values]
    cache-control = '''
    public,
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
    pragma = '''
    no-cache'''

[[redirects]]
    from = "/*"
    to = "https://block-development.netlify.app/404"
    status = 404