[[headers]]
    for = "/*"
    [headers.values]
    cache-control = '''
    public,
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
    pragma = '''
    no-cache'''
    X-Frame-Options = "DENY"
